### ISSUE TITLE
启动时报这个错如何解决？

### ISSUE THREAD

**Issue by liu790** [d78ui98/APKDeepLens#16]
Traceback (most recent call last):
  File "APKDeepLens.py", line 10, in <module>
    from report_gen import ReportGen, util
  File "E:\tools_App\APKDeepLens-main\APKDeepLens-main\report_gen.py", line 45, in <module>
    class ReportGen(object):
  File "E:\tools_App\APKDeepLens-main\APKDeepLens-main\report_gen.py", line 387, in ReportGen
    ) -> tuple["ReportGen", dict]:
TypeError: 'type' object is not subscriptable

**Comment by yingdushenyou** [comment]
我把python版本调整到python10 就解决了

**Comment by d78ui98** [comment]
@yingdushenyou 

Thank you for identifying the issue and providing a fix! I have also updated the codebase to ensure compatibility with all Python 3.x versions.

Feel free to test it out, and let me know if we can go ahead and close this issue. I really appreciate your time and contribution :)

**Comment by d78ui98** [comment]
I will go ahead and close this issue now. Feel free to reach out if you encounter any issues in the future. 
Thank you 😊
