### ISSUE TITLE
安装后发生错误

### ISSUE THREAD

**Issue by yingdushenyou** [d78ui98/APKDeepLens#19]
(venv) [root@VM-251-13-centos APKDeepLens]# python3.8 APKDeepLens.py --help
Traceback (most recent call last):
  File "APKDeepLens.py", line 10, in <module>
    from report_gen import ReportGen, util
  File "/root/APKDeepLens/report_gen.py", line 45, in <module>
    class ReportGen(object):
  File "/root/APKDeepLens/report_gen.py", line 387, in ReportGen
    ) -> tuple["ReportGen", dict]:
TypeError: 'type' object is not subscriptable

**Comment by yingdushenyou** [comment]
已经解决，将python升级到 3.10版本就OK了

**Comment by d78ui98** [comment]
Hello @yingdushenyou 

Thank you for identifying the issue. As discussed in https://github.com/d78ui98/APKDeepLens/issues/16
  I have updated the codebase to ensure compatibility across all Python 3.x versions. This issue will now be closed as it has been resolved. Please don’t hesitate to reach out if you have any questions or encounter any issues in the future.😊
