### ISSUE TITLE
Feature Request : Check Exported Status of Android Activities

### ISSUE THREAD

**Issue by nehajain444** [d78ui98/APKDeepLens#3]
Great work on the project so far.  It is very useful for initial analysis of APK files.

I would like to request a feature that checks if Android components (activities, services, receivers, providers) are exported. This can be done by analyzing the `android:exported` attribute. This feature will aid developers in ensuring the security and proper configuration of their Android components, enhancing app security and integrity.

**Comment by d78ui98** [comment]
Absolutely! I am working on this feature. It will be completed by this week.

**Comment by d78ui98** [comment]
I have update code to return the exported components.
Here is the screenshot for the output

![image](https://github.com/d78ui98/APKDeepLens/assets/27950739/a3a3e993-c051-4fdd-b26c-07d43051f098)

**Comment by nehajain444** [comment]
Great! This would be a nice edition to the project. Will come up more feature requests and will try to contribute as well.
Thank you.

**Comment by d78ui98** [comment]
Thank you as well. 
Looking forward for you pull requests :)
