### ISSUE TITLE
[Errno 2] No such file or directory: 'reports/report_smartplug.json' at line 268

### ISSUE THREAD

**Issue by Ashraful-alim** [d78ui98/APKDeepLens#5]
I have tried to test 2 different apk file and it shows me this error. I have also tried to test the sample apk file smartplug.apk.

![image](https://github.com/d78ui98/APKDeepLens/assets/33482997/e7cd7ee7-d534-49f8-bd09-b89742fe768f)

**Comment by jasonthename** [comment]
I'm also having the same error at that part of the script.

**Comment by d78ui98** [comment]
Hello @jasonthename @Ashraful-alim 

Thank you for bringing this to our attention. Your input is greatly valued :)
I addressed the issue you reported. 
Please check and let me know if it resolves the problem.

**Comment by jasonthename** [comment]
Its fixed thx.

**Comment by d78ui98** [comment]
Thank you for confirming @jasonthename 
You are welcome
